# Generated by Django 4.0.4 on 2022-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('autores', models.CharField(max_length=1000)),
                ('instituicao', models.CharField(max_length=1000)),
                ('datapubli', models.CharField(max_length=1000)),
                ('datacria', models.CharField(max_length=1000)),
                ('palachave', models.CharField(max_length=1000)),
                ('resumo', models.CharField(max_length=1000)),
                ('resume', models.CharField(max_length=1000)),
                ('referencias', models.CharField(max_length=1000)),
                ('direitos', models.CharField(max_length=200)),
            ],
        ),
    ]
