# Generated by Django 4.0.4 on 2022-06-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_artigos_direitos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigos',
            old_name='datacria',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='artigos',
            old_name='datapubli',
            new_name='dataPublicacao',
        ),
        migrations.RenameField(
            model_name='artigos',
            old_name='palachave',
            new_name='palavraChave',
        ),
        migrations.RemoveField(
            model_name='artigos',
            name='referencias',
        ),
    ]
