# Generated by Django 4.0.4 on 2022-06-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_datacria_artigos_abstract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigos',
            old_name='resume',
            new_name='doi',
        ),
        migrations.AddField(
            model_name='artigos',
            name='revista',
            field=models.CharField(default=1000, max_length=1000),
            preserve_default=False,
        ),
    ]
